apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.externalName }}
  ports:
  {{- range .Values.service.ports }}
  - port: {{ . }}
  {{- end }}
