apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claim.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.claim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.claim.size }}
